# Author: Fred Rothganger
# Copyright (c) 2001-2004 Dept. of Computer Science and Beckman Institute,
#                         Univ. of Illinois.  All rights reserved.
# Distributed under the UIUC/NCSA Open Source License.  See the file LICENSE
# for details.
#
#
# Revisions 1.4, 1.6 thru 1.8 Copyright 2005 Sandia Corporation.
# Revisions 1.9 and 1.10      Copyright 2007 Sandia Corporation.
# Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
# the U.S. Government retains certain rights in this software.
# Distributed under the GNU Lesser General Public License.  See the file
# LICENSE for details.
#
#
#------------------------------------------------------------------------------
# $Log$
# Revision 1.10  2007/03/23 12:05:06  Fred
# Use CVS Log to generate revision history.
#
# Revision 1.9  2006/02/03 14:24:56  Fred
# Add distclean rule.
# 
# Reorder the build sequence to be consistent with the library dependency
# structure.  This ensures that each shared library has all the shared
# libraries it needs at the time it is built.
# 
# Revision 1.8  2005/10/15 22:44:18  Fred
# Hack to make tar work.  Problem is that $(notdir ..) can't handle spaces in
# path names.  The previous version was more correct, since there's nothing to
# force the source directory to match the namespace.
# 
# Revision 1.7  2005/10/08 18:31:37  Fred
# Fix spelling of Lesser.
# 
# Revision 1.6  2005/10/08 18:10:35  Fred
# Update revision history and licensing info.
# 
# Add quotes around certain paths to make Cygwin work in the "Documents and
# Settings" directory.
# 
# Adjust directories excluded from distribution.
# 
# Revision 1.5  2005/04/23 19:34:19  Fred
# Add UIUC copyright notice.  Note files that I revised after leaving UIUC on
# 11/21.
# 
# Revision 1.4  2005/01/22 20:31:43  Fred
# MSVC compilability fix: Remove files generated by build.
# 
# Revision 1.3  2004/09/08 17:09:12  rothgang
# Exclude ideas from distribution.
# 
# Revision 1.2  2004/08/02 15:20:29  rothgang
# Add Doxygen.
# 
# Break installation up by type of material.
# 
# Compile libraries before utilities, so utilities can use the libraries.
# 
# Revision 1.1  2003/07/08 23:19:47  rothgang
# branches:  1.1.1;
# Initial revision
# 
# Revision 1.1.1.1  2003/07/08 23:19:47  rothgang
# Imported sources
#------------------------------------------------------------------------------


SOURCE_DIR := $(CURDIR)
-include Config


# Some programs in util require the libraries to be built first.
PACKAGES = base net numeric image X util

default: all
all: $(PACKAGES)

.DEFAULT:
	$(MAKE) -C src/$@


.PHONY: default all doc clean install depend tar changens

doc:
	doxygen

topclean:
	rm -f *~ include/$(NS)/*~ $(NS).tgz changens.sed
	rm -f *.ncb *.suo lib/*.lib
	rm -rf html man

clean: topclean
	for PACKAGE in $(PACKAGES); do $(MAKE) -C src/$$PACKAGE clean; done

distclean: topclean
	for PACKAGE in $(PACKAGES); do $(MAKE) -C src/$$PACKAGE distclean; done

depend:
	for PACKAGE in $(PACKAGES); do $(MAKE) -C src/$$PACKAGE depend; done

install-headers:
	mkdir -p "$(INSTALL_INC)"/$(NS)
	cp -Ruv "$(SOURCE_INC)"/$(NS)/*.h "$(INSTALL_INC)"/$(NS)

install-libs:
	mkdir -p "$(INSTALL_LIB)"
	cp -Ruv "$(SOURCE_LIB)"/* "$(INSTALL_LIB)"

install-bin:
	mkdir -p "$(INSTALL_BIN)"
	cp -Ruv "$(SOURCE_BIN)"/* "$(INSTALL_BIN)"
	find "$(SOURCE_DIR)"/script -maxdepth 1 -not \( -name "*~" -or -type d \) -exec cp -v \{\} "$(INSTALL_BIN)" \;

install-doc:
	mkdir -p "$(INSTALL_HTML)"
	cp -Ruv "$(SOURCE_HTML)"/* "$(INSTALL_HTML)"
	mkdir -p "$(INSTALL_MAN)"
	cp -Ruv "$(SOURCE_MAN)"/* "$(INSTALL_MAN)"

install: all install-headers install-libs install-bin #install-doc

tar: distclean
	tar -czvf $(NS).tgz --exclude=*.tgz --exclude=CVS --exclude=private --exclude=mswin --no-anchored -C .. $(NS)

# If you prefer to place the library in a different namespace,
# set OLDNS and NS in Config appropriately, then do "make changens".
changens: distclean
	sed -e s/oldns/$(OLDNS)/g -e s/ns/$(NS)/g < changens.template > changens.sed
	for PACKAGE in $(PACKAGES); do cd $(SOURCE_DIR)/src/$$PACKAGE; ../../changens.sh; done
	(cd $(SOURCE_DIR)/include; mv $(OLDNS) $(NS); exit 0)
	cd $(SOURCE_DIR)/include/$(NS);	../../changens.sh
	for PACKAGE in $(PACKAGES); do $(MAKE) -C src/$$PACKAGE depend; done
